- name: Configure Chrony NTP Service (RHEL Host)
  hosts: all
  gather_facts: yes
  become: yes

  vars:
    chrony_conf: "/etc/chrony/chrony.conf"          # chrony
    custom_ntp_server: "time.cloudflare.com"       # Network Time Protocol server
    allowed_network: "192.168.1.0/24"             # Who gets to play with our clock
    chrony_log_dir: "/var/log/chrony"             # Logging

  tasks:

    # Neat line for config
    # Makes life easier =no spaghetti
    - name: Set dynamic facts
      set_fact:
        chrony_allow_line: "allow {{ allowed_network }}"

    # Log location
    - name: Show selected log directory
      debug:
        msg: "Chrony logs will be stored at: {{ chrony_log_dir }}"

    # Make sure the config directory exists avoid failures in conf/writing logs
    # Idempotent, will only create directory if missing
    - name: Ensure chrony config directory exists
      file:
        path: /etc/chrony
        state: directory
        owner: root
        group: root
        mode: '0755'

    # Make sure logs exist too for idempotency
    - name: Ensure chrony log directory exists
      file:
        path: "{{ chrony_log_dir }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    # Copy over the main config. Will restart if Chrony changes
    - name: Deploy main chrony config
      copy:
        src: chrony.conf
        dest: "{{ chrony_conf }}"
        owner: root
        group: root
        mode: '0644'
      notify: Restart chrony

    # lineinfile and regexp to avoid duplicates. 
    # Idempotent if line exists = no change
    - name: Ensure custom NTP server is in config
      lineinfile:
        path: "{{ chrony_conf }}"
        regexp: '^server {{ custom_ntp_server }}'
        line: "server {{ custom_ntp_server }} iburst"
        insertafter: EOF
        state: present
        backrefs: yes
      notify: Restart chrony

    # Defines networks/clients that can query our NTP server
    # Chrony_allow_line variable makes idempotent I think
    - name: Ensure allowed network exists in config
      lineinfile:
        path: "{{ chrony_conf }}"
        regexp: '^allow {{ allowed_network }}'
        line: "{{ chrony_allow_line }}"
        insertafter: EOF
        state: present
        backrefs: yes
      notify: Restart chrony

    # Make sure Chrony is actually running
    - name: Enable and start chrony service
      service:
        name: chronyd
        state: started
        enabled: yes

  handlers:
    # Only restart when needed
    - name: Restart chrony
      service:
        name: chronyd
        state: restarted
